### ISSUE TITLE
Course Completion Certificate

### ISSUE THREAD

**Issue by vinivirtus** [ModernAppsNinja/vspheretanzu201_vt4599#364]
Hi Time ModernAppninja, to last step to complete course I m  receive error bellow.

0s
1
Run jq -r '.[].name' /tmp/grading_stub_list.json > /tmp/grading_stub_name_list.pre
12
jq: error (at /tmp/grading_stub_list.json:4): Cannot index string with string "name"
13
Error: Process completed with exit code 5.

**Comment by afewell** [comment]
Hi @vinivirtus it looks like the problem is because while you completed the tests in this course, it is also needed to enroll in this (and each) course by posting a file to the https://github.com/ModernAppsNinja/vspheretanzu201_vt4599/tree/main/static/admin/userdata/registered_members directory

The reason for this is, when you post this file, it triggers a Github action workflow that sets up your member repo/page to display that you are enrolled in this course and prepare it for hosting your course records. I hope with some time I am able to get in better error handling, as the system should have ideally given you a clear error message when you took the first test. Fortunately the test service did properly save your test records, so I think/hope to get your member page updated properly, all you should need to do is enroll in this course, and then if you repeat the step to post a file to the certs_awarded directory, that should retrigger the script to award your cert, which should work as long as you have completed course enrollment. I havent tested it thoroughly in that non-standard order, but I think it should work, and if it doesnt I will get things patched up manually if needed.

If you could try those steps and let me know how it goes, I will follow up with you to ensure this gets patched up. I do have a few members of my team out on leave right now and its an extra busy time as we prepare for SpringOne and VMworld so apologies in advance as I may be a bit slower to respond than usual. thanks!
